<?php
$id = '';
$data_melisKey = '';

$id = ' id="' . $this->id . '"';

if (!empty($this->melisKey))
    $data_melisKey = ' data-meliskey="' . $this->melisKey . '"';

?>
<div>
    <div class="modal fade" id="<?php echo $this->id?>_container">
        <div class="modal-dialog" role="modal">
            <div id="melis_platform_framework_lumen_demo_tool_modal_content" data-meliskey="melis_platform_framework_lumen_demo_tool_modal_content" class="modal-content"></div>
        </div>
    </div>
</div>