<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>
<div<?= $id; ?>  class="tab-pane container-level-a" data-melisKey='<?= $this->melisKey; ?>'>
    <div class="me-heading bg-white">
        <div class="row">
            <div class="me-hl col-xs-12 col-sm-12 col-md-12">
                <h1 class="content-heading"><?= $this->translate('tr_melis_code_example_lumen_tool_head_title')?></h1>
                <p><?= $this->translate('tr_melis_code_example_lumen_tool_head_desc') ?> </p>
            </div>
        </div>
    </div>
    <div class="innerAll spacing-x2">
        <?= $this->lumen ?>
        <?php
        if(!empty($this->zoneconfig['interface'])) {
            foreach($this->zoneconfig['interface'] as $keyConfig => $menuConfig) {
                echo $this->$keyConfig;
            }
        }
        ?>
    </div>
</div>
